### ISSUE TITLE
'unless' it is not recognized as 'unless_statement'

### ISSUE THREAD

**Issue by misaflo** [amaanq/tree-sitter-puppet#4]
Hi,

Thank for tree-sitter for Puppet.

`unless` is recognized as identifier, and is not highlight as `if` or `else`. Can you add `unless_statement`?

**Comment by amaanq** [comment]
Thanks for the report! I'm a bit surprised that puppet's core repo didn't use this anywhere for me to notice this fail (that's what I test on). Fixed on master

**Comment by misaflo** [comment]
Thanks!
